version: '3.8'

services:
  jsonmapper:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4}
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add PostgreSQL for future database support
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=jsonmapper
  #     - POSTGRES_USER=jsonmapper
  #     - POSTGRES_PASSWORD=jsonmapper
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  # postgres_data:
